# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e894a895ca009691f8247149e83420de871414a145fc86ea4a7eb20c68116d7d4624f48ef75bbf599f44c8a12aa1ba5ae9e278add9b22c0830bc68544f105a7d

test:
  secret_key_base: fee179017723c8c5a8eaf3ef45c12654c513721ea9d822b53bb458d3022421350646956330353bfbb00028a6c4ad2c3fe31a733614bc6c5c4158f83e54187ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
